name: cnc_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+57

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  data_table_2: ^2.5.18
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
